export default [
  'Are you friends with more men or women?',
  'Are you religious?',
  'Can you play an instrument?',
  'Do you have a temper?',
  'Do you have any allergies?',
  'Do you have any nicknames?',
  'Do you have any pet peeves?',
  'Do you have any siblings?',
  'Do you have any tattoos or piercings?',
  'Do you have family in another country?',
  'Do you have nice handwriting?',
  'Do you have pets?',
  'Do you keep your things organized?',
  'Do you know any jokes?',
  'Do you like bugs?',
  'Do you like flying?',
  'Do you like ice in your drinks?',
  'Do you like roller coasters?',
  'Do you like the beach?',
  'Do you like to dance?',
  'Do you like your job?',
  'Do you swear often?',
  'Have you ever been a vegetarian?',
  'Have you ever been arrested?',
  'Have you ever been done karaoke?',
  'Have you ever been electrocuted?',
  'Have you ever been horseback riding?',
  'Have you ever been hunting?',
  'Have you ever been in a fight?',
  'Have you ever been in a play?',
  'Have you ever been in a talent show?',
  'Have you ever been in a tree house?',
  'Have you ever been on TV?',
  'Have you ever been scuba diving?',
  'Have you ever been skiing?',
  'Have you ever been slapped?',
  'Have you ever been stopped by the police?',
  'Have you ever been surfing?',
  'Have you ever been tanning?',
  'Have you ever been to a farm?',
  'Have you ever been to a football game?',
  'Have you ever been to a planetarium?',
  'Have you ever been to a Renaissance fair?',
  'Have you ever been to a zoo?',
  'Have you ever been to Africa?',
  'Have you ever been to Asia?',
  'Have you ever been to Comic-con?',
  'Have you ever been to South America?',
  'Have you ever been water skiing?',
  'Have you ever broken a bone?',
  'Have you ever bungee jumped?',
  'Have you ever burnt your hair?',
  'Have you ever changed a diaper?',
  'Have you ever changed a tire?',
  'Have you ever cheated on a test?',
  "Have you ever cut someone else's hair?",
  'Have you ever cut your own hair?',
  'Have you ever dined and dashed?',
  'Have you ever dyed your hair?',
  'Have you ever eaten food from the trash?',
  'Have you ever eaten sushi?',
  'Have you ever fainted?',
  'Have you ever gotten stitches?',
  'Have you ever had bad sun burn?',
  'Have you ever had to run for your life?',
  'Have you ever hitchhiked?',
  'Have you ever ironed clothes?',
  'Have you ever jumped out of a plane?',
  'Have you ever mowed a lawn?',
  'Have you ever ran in a race?',
  'Have you ever ridden a motorcycle?',
  'Have you ever seen a ghost?',
  'Have you ever sewed?',
  'Have you ever shoplifted?',
  'Have you ever shot a gun?',
  'Have you ever slept outside?',
  'How many books did you read last year?',
  'How many children do you want?',
  'How many pairs of shoes do you own?',
  'If you could become invisible, what would you do?',
  'If you could change genders for a day, would you?',
  'If you could have a superpower, what would you choose?',
  'If you could have any kind of pet, what would you choose?',
  'If you could learn any language, what would you choose?',
  'If you could meet anyone, who would you choose?',
  'If you could play any instrument, what would you choose?',
  'If you could time travel, what would you do?',
  "If you didn't need sleep, what would you do?",
  'If you had to become an animal, what would you choose?',
  'If you had to change your name, what would you choose?',
  'If you had to eat just one thing forever, what it be?',
  'If you had to live somewhere else, where would it be?',
  'If you had to swap lives with a character, who would it be?',
  'If you had to swap lives with someone famous, who would it be?',
  'If you won the lottery, what would you buy?',
  'What are your favorite albums?',
  'What are your favorite books?',
  'What are your favorite hot dog toppings?',
  'What are your favorite ice cream toppings?',
  'What are your favorite movies?',
  'What are your favorite songs?',
  'What do you always buy at the grocery store?',
  'What do you do as excerise?',
  'What do you do to make money?',
  'What do you fear?',
  "What is the longest you've been awake?",
  "What is the scarest animal you've seen in the wild?",
  "What is the strangest thing you've eaten?",
  "What is the worst movie you've seen?",
  'What is you favorite snack?',
  'What is your favorite board game?',
  'What is your favorite breakfast meal?',
  'What is your favorite candy?',
  'What is your favorite cereal?',
  'What is your favorite cheese?',
  'What is your favorite clothing brand?',
  'What is your favorite color to wear?',
  'What is your favorite color?',
  'What is your favorite comedy?',
  'What is your favorite dessert?',
  'What is your favorite dinner meal?',
  'What is your favorite Disney movie?',
  'What is your favorite drink?',
  'What is your favorite eye color?',
  'What is your favorite fast food meal?',
  'What is your favorite flavor of ice cream?',
  'What is your favorite food to cook?',
  'What is your favorite fruit?',
  'What is your favorite hair color?',
  'What is your favorite holiday?',
  'What is your favorite lunch meal?',
  'What is your favorite memory?',
  'What is your favorite month?',
  'What is your favorite sandwich?',
  'What is your favorite school subject?',
  'What is your favorite season?',
  'What is your favorite sport?',
  'What is your favorite TV show?',
  'What is your favorite vacation?',
  'What is your favorite video game?',
  'What is your first memory?',
  'What is your least favorite chore?',
  'What is your size shoe?',
  'What type of music are you into?',
  'What was your major in school?',
  'What was your worst injury?',
  'When is your birthday?',
  'Where are you originally from?',
  'Where did you get your name?',
  'Where did you go to school?',
  'Where do you see yourself in ten years?',
  'Where have you traveled?',
  "Where is the furthest you've driven?",
  "Where is the furthest you've traveled?",
  'Where is you favorite place to eat?',
  'Which do you like better, beer or wine?',
  'which do you like better, being a passenger or driver?',
  'Which do you like better, black socks or white socks?',
  'Which do you like better, book or eBook?',
  'Which do you like better, cake or pie?',
  'which do you like better, calls or texts?',
  'Which do you like better, cardio or weightlifting?',
  'Which do you like better, cars or trucks?',
  'Which do you like better, chocolate or vanilla?',
  'Which do you like better, city or country?',
  'Which do you like better, coffee or tea?',
  'Which do you like better, Coke or Pepsi?',
  'Which do you like better, comedy or drama?',
  'Which do you like better, curtains or blinds?',
  'Which do you like better, dogs or cats?',
  'Which do you like better, Google or Apple?',
  'Which do you like better, hot or cold?',
  'Which do you like better, long hair or short hair?',
  'Which do you like better, Microsoft or Apple?',
  'Which do you like better, morning or night?',
  'Which do you like better, mountains or oceans?',
  'Which do you like better, ninjas or pirates?',
  'Which do you like better, pancakes or waffles?',
  'Which do you like better, pens or pencils?',
  'Which do you like better, rain or snow?',
  'Which do you like better, shop online or shop offline?',
  'Which do you like better, shower or bath?',
  'Which do you like better, Star Wars or Star Trek?',
  'Which do you like better, straight or curly?',
  'Which do you like better, sweet or salty?',
  'Which do you like better, TV or movies?',
  'Who do you most resemble?',
  'Who is your favorite character?'
];
